// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOPMqh-czv1KB8ONSjslcJPtB7OboYSU',
    appId: '1:514040233101:web:36ef0c825c1abf739176c4',
    messagingSenderId: '514040233101',
    projectId: 'snakegame-4a476',
    authDomain: 'snakegame-4a476.firebaseapp.com',
    storageBucket: 'snakegame-4a476.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWYNrtG-gLA0jUGUiAFquLwdSYVDKV04',
    appId: '1:514040233101:android:d80a770285cd34e89176c4',
    messagingSenderId: '514040233101',
    projectId: 'snakegame-4a476',
    storageBucket: 'snakegame-4a476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo7V38x4OzngS4vZvUUIpwEE6WGTGGuHo',
    appId: '1:514040233101:ios:6fd1575f50c977e89176c4',
    messagingSenderId: '514040233101',
    projectId: 'snakegame-4a476',
    storageBucket: 'snakegame-4a476.appspot.com',
    iosBundleId: 'com.example.starter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo7V38x4OzngS4vZvUUIpwEE6WGTGGuHo',
    appId: '1:514040233101:ios:0ce0e7a5ca7731b19176c4',
    messagingSenderId: '514040233101',
    projectId: 'snakegame-4a476',
    storageBucket: 'snakegame-4a476.appspot.com',
    iosBundleId: 'com.example.starter.RunnerTests',
  );
}
